### ISSUE TITLE
[FIx] 1차 QA 반영

### ISSUE THREAD

**Issue by Padoari** [ADA-RLD/PostKit#254]
📕 Issue Feature
1차 QA에서 배정된 작업들을 처리합니다.

**Comment by kdb1217** [comment]
배정된 작업보다는 정확환 테스크를 입력하는게 좋을 것 같아요!

**Comment by Padoari** [comment]
> 배정된 작업보다는 정확환 테스크를 입력하는게 좋을 것 같아요!

의견 감사합니다
